#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class SoundIdGenerator
{
    private const string OutputPath = "Assets/_Audio/Scripts/Generated/SoundId.generated.cs";

    [MenuItem("Tools/JamAudio/Regenerate SoundId Enum")]
    public static void RegenerateMenu()
    {
        string[] guids = AssetDatabase.FindAssets("t:SoundLibrary");
        if (guids == null || guids.Length == 0)
        {
            Debug.LogWarning("[JamAudio] No SoundLibrary found.");
            return;
        }

        string path = AssetDatabase.GUIDToAssetPath(guids[0]);
        SoundLibrary lib = AssetDatabase.LoadAssetAtPath<SoundLibrary>(path);
        Generate(lib);
    }

    public static void Generate(SoundLibrary lib)
    {
        if (lib == null) return;

        // Find ALL SoundCue assets in the project
        string[] cueGuids = AssetDatabase.FindAssets("t:SoundCue");
        var allCues = cueGuids
            .Select(guid =>
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                return AssetDatabase.LoadAssetAtPath<SoundCue>(path);
            })
            .Where(cue => cue != null)
            .Distinct()
            .ToList();

        // Stable ordering by GUID (so enum values don't reshuffle randomly)
        allCues = allCues
            .Select(cue => new
            {
                cue,
                guid = AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(cue))
            })
            .OrderBy(x => x.guid, StringComparer.Ordinal)
            .Select(x => x.cue)
            .ToList();

        // Put that list into the library for runtime
        lib.cues = allCues;
        EditorUtility.SetDirty(lib);

        var sb = new StringBuilder();
        sb.AppendLine("/// <auto-generated>");
        sb.AppendLine("/// This file is generated by SoundIdGenerator.cs");
        sb.AppendLine("/// Do not edit manually.");
        sb.AppendLine("/// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Enum of all sounds in the project (stable by asset GUID).</summary>");
        sb.AppendLine("public enum SoundId");
        sb.AppendLine("{");

        if (lib.cues.Count == 0)
        {
            sb.AppendLine("    _0 = 0,");
        }
        else
        {
            for (int i = 0; i < lib.cues.Count; i++)
            {
                SoundCue cue = lib.cues[i];
                string raw  = cue.GetEffectiveIdName();
                string safe = MakeSafeIdentifier(raw);

                // Handle duplicates after sanitization by suffixing index
                if (lib.cues.Count(c => MakeSafeIdentifier(c.GetEffectiveIdName()) == safe) > 1)
                    safe = $"{safe}_{i}";

                sb.AppendLine($"    {safe} = {i},");
            }
        }

        sb.AppendLine("}"); // enum

        Directory.CreateDirectory(Path.GetDirectoryName(OutputPath));
        File.WriteAllText(OutputPath, sb.ToString(), Encoding.UTF8);

        AssetDatabase.ImportAsset(OutputPath);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log($"[JamAudio] Regenerated SoundId enum ({lib.cues.Count} cues) at {OutputPath}");
    }

    private static string MakeSafeIdentifier(string s)
    {
        if (string.IsNullOrWhiteSpace(s)) return "_0";

        var chars = s.Trim().Select(ch =>
        {
            if (char.IsLetterOrDigit(ch)) return ch;
            return '_';
        }).ToArray();

        string result = new string(chars);

        if (char.IsDigit(result[0]))
            result = "_" + result;

        while (result.Contains("__"))
            result = result.Replace("__", "_");

        return result;
    }
}

[CustomEditor(typeof(SoundLibrary))]
public sealed class SoundLibraryEditor : UnityEditor.Editor
{
    public override void OnInspectorGUI()
    {
        DrawDefaultInspector();

        GUILayout.Space(8);
        if (GUILayout.Button("Regenerate SoundId Enum"))
        {
            SoundIdGenerator.Generate((SoundLibrary)target);
        }
    }
}
#endif
