#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

public static class SoundIdGenerator
{
    private const string OutputPath = "Assets/_Audio/Scripts/Generated/SoundId.generated.cs";

    public static void Generate(SoundLibrary lib)
    {
        if (lib == null) return;

        // ✅ NEW: delete any old AUTO-GENERATED SoundId definitions anywhere
        DeleteOldGeneratedSoundIdDefinitions();

        // (optional) also keep your folder cleanup if you want
        // DeleteOldGeneratedScriptsInOutputFolder();

        // ... then write OutputPath as you already do
    }

    private static void DeleteOldGeneratedSoundIdDefinitions()
    {
        // Find any script that might contain SoundId (name or content indexing)
        var guids = AssetDatabase.FindAssets("SoundId t:Script");
        string outputPathNorm = OutputPath.Replace('\\', '/');

        foreach (var guid in guids)
        {
            string assetPath = AssetDatabase.GUIDToAssetPath(guid).Replace('\\', '/');

            // never delete the one we're about to generate (it may exist already)
            if (string.Equals(assetPath, outputPathNorm, StringComparison.OrdinalIgnoreCase))
                continue;

            // Read file and only delete if it's clearly auto-generated AND defines enum SoundId
            string fullPath = Path.GetFullPath(assetPath);
            if (!File.Exists(fullPath))
                continue;

            string text = File.ReadAllText(fullPath);

            bool isAutoGenerated = text.Contains("<auto-generated>", StringComparison.OrdinalIgnoreCase);
            bool definesSoundIdEnum = text.Contains("enum SoundId", StringComparison.Ordinal);

            if (isAutoGenerated && definesSoundIdEnum)
            {
                bool deleted = AssetDatabase.DeleteAsset(assetPath);
                if (deleted)
                    Debug.Log($"[JamAudio] Deleted old generated SoundId file: {assetPath}");
            }
        }
    }
}
#endif
